services:
  # Web API Service
  - type: web
    name: 4kvideoreaper-api
    env: docker
    region: ohio
    plan: free
    healthCheckPath: /api/status
    buildCommand: bash render-build.sh
    startCommand: gunicorn --log-level=debug --workers=1 --timeout=120 --bind=0.0.0.0:$PORT web.wsgi:app
    envVars:
      - key: DOWNLOAD_DIR
        value: /tmp/downloads
      - key: LOG_DIR
        value: /tmp/logs
      - key: ARIA2_ENABLED
        value: "true"
      - key: PYTHONPATH
        value: /app
      - key: ENVIRONMENT
        value: production
